# Generated by Django 5.2.8 on 2025-12-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='images/blog'),
            preserve_default=False,
        ),
    ]
